name: Create a dev pro release

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    name: "build"
    strategy:
      matrix:
        go: [stable]
        os:
        - ubuntu-latest
        - macos-latest
        arch:
        - arm64
        - amd64
    runs-on: ${{ matrix.os }}
    env:
      GOPRIVATE: "github.com/humanlogio/humanlog-pro"
      GH_ACCESS_TOKEN_FOR_HUMANLOGPRO: ${{ secrets.GH_ACCESS_TOKEN_FOR_HUMANLOGPRO }}
      GOARCH: ${{ matrix.arch }}
      CGO_ENABLED: 1
    steps:
      - name: Set up Go 1
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: true
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git config --global --add safe.directory '*'
      - run: git config --global url.https://$GH_ACCESS_TOKEN_FOR_HUMANLOGPRO@github.com/.insteadOf https://github.com/
      - run: go install github.com/goware/modvendor@latest
      - run: go mod vendor
      - run: modvendor -copy="**/*.a **/*.h" -v
      - run: go build -tags pro -o /tmp/humanlog-${{ matrix.os }}-${{ matrix.arch }} ./cmd/humanlog
