name: Create a dev release

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  create_a_dev_release:
    name: create a dev release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.23"
          cache: true
      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --config .goreleaser-dev.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
      - run: echo "${HOME}/.humanlog/bin" >> $GITHUB_PATH
      - run: curl https://humanlog.dev/install_apictl.sh | bash
      - run: ./script/create_version_artifacts.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HMAC_KEY_ID: ${{ secrets.HMAC_KEY_ID }}
          HMAC_PRIVATE_KEY: ${{ secrets.HMAC_PRIVATE_KEY }}
