name: Create a release

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  create_a_release:
    name: create a release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.23"
          cache: true
      - run: echo "${HOME}/.humanlog/bin" >> $GITHUB_PATH
      - run: curl https://humanlog.io/install_apictl.sh | bash
      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: v2
          args: release --clean --config .goreleaser.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
      - run: ./script/create_version_artifacts.sh
        env:
          CHANNEL: "main"
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          API_URL: "https://api.humanlog.io"
          HMAC_KEY_ID: ${{ secrets.PROD_HMAC_KEY_ID }}
          HMAC_PRIVATE_KEY: ${{ secrets.PROD_HMAC_PRIVATE_KEY }}
